import logging

import flask
from flask import request, jsonify
from flask_login import login_required, current_user

from . import cms_bp
from ..models import db, ApiKey
from ..auth import admin_required, apply_tenant_filter, ensure_tenant_access

from .response import api_success, api_error

logger = logging.getLogger(__name__)


@cms_bp.route("/api/api-keys", methods=["GET"])
@login_required
@admin_required
def list_api_keys() -> flask.Response:
    keys = apply_tenant_filter(
        ApiKey.query.order_by(ApiKey.created_at.desc()), ApiKey
    ).all()
    return jsonify(
        [
            {
                "id": k.id,
                "name": k.name,
                "prefix": k.key_prefix + "...",
                "scopes": k.scopes or ["read"],
                "is_active": k.is_active,
                "last_used_at": k.last_used_at.isoformat() if k.last_used_at else None,
                "created_at": k.created_at.isoformat() if k.created_at else None,
                "created_by": k.creator.username if k.creator else "unknown",
            }
            for k in keys
        ]
    )


@cms_bp.route("/api/api-keys/generate", methods=["POST"])
@login_required
@admin_required
def generate_api_key() -> flask.Response:
    from ..tier_limits import check_feature

    if not check_feature("api_keys"):
        return api_error(
            "API keys are not available on your current plan. Upgrade to access this feature.",
            403,
        )
    data = request.get_json(silent=True) or {}
    name = (data.get("name") or "").strip()
    if not name:
        return api_error("Name is required", 400)
    if len(name) > 100:
        return api_error("Name too long (max 100 chars)", 400)

    raw_key, key_hash = ApiKey.generate_key()
    prefix = raw_key[:8]

    valid_scopes = {"read", "write", "admin"}
    raw_scopes = data.get("scopes", ["read"])
    scopes = [s for s in raw_scopes if s in valid_scopes] or ["read"]

    key = ApiKey(
        name=name,
        key_hash=key_hash,
        key_prefix=prefix,
        user_id=data.get("user_id", current_user.id),
        scopes=scopes,
        is_active=True,
    )
    db.session.add(key)
    db.session.commit()

    logger.info(
        "API key '%s' generated by %s (scopes: %s)", name, current_user.username, scopes
    )

    return jsonify(
        {
            "id": key.id,
            "name": key.name,
            "key": raw_key,
            "prefix": prefix,
            "scopes": scopes,
            "warning": "Copy this key now — it will not be shown again.",
        }
    ), 201


@cms_bp.route("/api/api-keys/<key_id>/revoke", methods=["POST"])
@login_required
@admin_required
def revoke_api_key(key_id: str) -> flask.Response:
    key = db.session.get(ApiKey, key_id)
    if not key:
        return api_error("API key not found", 404)
    ensure_tenant_access(key)

    key.is_active = False
    db.session.commit()

    logger.info("API key '%s' revoked by %s", key.name, current_user.username)
    return api_success({}, f"API key '{key.name}' revoked")


@cms_bp.route("/api/api-keys/<key_id>/delete", methods=["POST"])
@login_required
@admin_required
def delete_api_key(key_id: str) -> flask.Response:
    key = db.session.get(ApiKey, key_id)
    if not key:
        return api_error("API key not found", 404)
    ensure_tenant_access(key)

    db.session.delete(key)
    db.session.commit()

    logger.info("API key '%s' deleted by %s", key.name, current_user.username)
    return api_success({}, f"API key '{key.name}' deleted")
