"""initial_schema

Revision ID: 8c4bb90d2490
Revises:
Create Date: 2026-05-25 18:26:45.386947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import cms.models  # noqa: F401 — provides SafeJSON type


# revision identifiers, used by Alembic.
revision: str = "8c4bb90d2490"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_company", sa.Boolean(), nullable=True),
        sa.Column("date_of_birth", sa.String(length=500), nullable=True),
        sa.Column("place_of_birth", sa.String(length=500), nullable=True),
        sa.Column("contact_person", sa.String(length=500), nullable=True),
        sa.Column("contact_email", sa.String(length=500), nullable=True),
        sa.Column("contact_phone", sa.String(length=500), nullable=True),
        sa.Column("address_street", sa.String(length=500), nullable=True),
        sa.Column("address_number", sa.String(length=500), nullable=True),
        sa.Column("address_city", sa.String(length=500), nullable=True),
        sa.Column("address_postal", sa.String(length=500), nullable=True),
        sa.Column("address_country", sa.String(length=500), nullable=True),
        sa.Column("contract_number", sa.String(length=500), nullable=True),
        sa.Column("contract_info", sa.Text(), nullable=True),
        sa.Column("social_security_number", sa.String(length=500), nullable=True),
        sa.Column("vat_number", sa.String(length=500), nullable=True),
        sa.Column("bank_account", sa.String(length=500), nullable=True),
        sa.Column("financial_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_clients_name"), ["name"], unique=False)

    op.create_table(
        "subjects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("date_of_birth", sa.String(length=500), nullable=True),
        sa.Column("place_of_birth", sa.String(length=500), nullable=True),
        sa.Column("nationality", sa.String(length=500), nullable=True),
        sa.Column("identification_number", sa.String(length=500), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=500), nullable=True),
        sa.Column("email", sa.String(length=500), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_factors", cms.models.SafeJSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("legal_form", sa.String(length=100), nullable=True),
        sa.Column("asset_type", sa.String(length=50), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("social_media_ids", cms.models.SafeJSON(), nullable=True),
        sa.Column("license_plate", sa.String(length=500), nullable=True),
        sa.Column("vin", sa.String(length=500), nullable=True),
        sa.Column("insurance_company", sa.String(length=500), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("vehicle_type", sa.String(length=50), nullable=True),
        sa.Column("imo_number", sa.String(length=500), nullable=True),
        sa.Column("mmsi", sa.String(length=500), nullable=True),
        sa.Column("eni_number", sa.String(length=500), nullable=True),
        sa.Column("vessel_nationality", sa.String(length=500), nullable=True),
        sa.Column("vessel_data", cms.models.SafeJSON(), nullable=True),
        sa.Column("rdw_data", cms.models.SafeJSON(), nullable=True),
        sa.Column("photo_path", sa.String(length=500), nullable=True),
        sa.Column("face_encoding", cms.models.SafeJSON(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subjects_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("backup_codes", sa.Text(), nullable=True),
        sa.Column("password_reset_token", sa.String(length=128), nullable=True),
        sa.Column("password_reset_expires", sa.DateTime(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "addresses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("street", sa.String(length=500), nullable=True),
        sa.Column("number", sa.String(length=500), nullable=True),
        sa.Column("zipcode", sa.String(length=500), nullable=True),
        sa.Column("town", sa.String(length=500), nullable=True),
        sa.Column("country", sa.String(length=500), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("kadaster_verified", sa.Boolean(), nullable=True),
        sa.Column("kadaster_data", cms.models.SafeJSON(), nullable=True),
        sa.Column("kadaster_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("addresses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_addresses_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_addresses_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=8), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("scopes", cms.models.SafeJSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("changes_made", cms.models.SafeJSON(), nullable=True),
        sa.Column("old_values", cms.models.SafeJSON(), nullable=True),
        sa.Column("new_values", cms.models.SafeJSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_number", sa.String(length=50), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("target_end_date", sa.Date(), nullable=True),
        sa.Column("actual_end_date", sa.Date(), nullable=True),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("lead_investigator_id", sa.String(length=36), nullable=True),
        sa.Column("case_type", sa.String(length=100), nullable=True),
        sa.Column("jurisdiction", sa.String(length=100), nullable=True),
        sa.Column("tags", cms.models.SafeJSON(), nullable=True),
        sa.Column("reopened_reason", sa.Text(), nullable=True),
        sa.Column("reopened_at", sa.DateTime(), nullable=True),
        sa.Column("reopened_by", sa.String(length=36), nullable=True),
        sa.Column("parent_case_id", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_investigator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reopened_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cases_case_number"), ["case_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_cases_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cases_title"), ["title"], unique=False)

    op.create_table(
        "contacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("contact_type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contacts_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contacts_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "document_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_type", sa.String(length=50), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "phone_lookups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("raw_response", cms.models.SafeJSON(), nullable=False),
        sa.Column("profile_picture", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("phone_lookups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_phone_lookups_phone"), ["phone"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("value_type", sa.String(length=20), nullable=True),
        sa.Column("options", cms.models.SafeJSON(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settings_category"), ["category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_settings_key"), ["key"], unique=True)

    op.create_table(
        "social_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("account_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_social_accounts_platform"), ["platform"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_social_accounts_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_social_accounts_username"), ["username"], unique=False
        )

    op.create_table(
        "subject_relations",
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("related_subject_id", sa.String(length=36), nullable=False),
        sa.Column("relationship_type", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "related_subject_id"),
    )
    op.create_table(
        "case_assignments",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("assigned_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("case_id", "user_id"),
    )
    op.create_table(
        "case_subjects",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("case_id", "subject_id"),
    )
    op.create_table(
        "financial_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("counterparty_name", sa.String(length=500), nullable=True),
        sa.Column("counterparty_account", sa.String(length=500), nullable=True),
        sa.Column("counterparty_bank", sa.String(length=500), nullable=True),
        sa.Column("counterparty_country", sa.String(length=500), nullable=True),
        sa.Column("transaction_type", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("source_reference", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=True),
        sa.Column("verified_by", sa.String(length=36), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("reliability_score", sa.Integer(), nullable=True),
        sa.Column("confidence_level", sa.String(length=20), nullable=True),
        sa.Column("finding_type", sa.String(length=50), nullable=True),
        sa.Column("tags", cms.models.SafeJSON(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_findings_case_id"), ["case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_findings_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "osint_searches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("search_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("results", cms.models.SafeJSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("started_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("osint_searches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_osint_searches_search_id"), ["search_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_osint_searches_status"), ["status"], unique=False
        )

    op.create_table(
        "reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reminder_date", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("reminder_type", sa.String(length=20), nullable=True),
        sa.Column("recurrence", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("is_overdue", sa.Boolean(), nullable=True),
        sa.Column("is_dismissed", sa.Boolean(), nullable=True),
        sa.Column("notify_email", sa.Boolean(), nullable=True),
        sa.Column("notify_dashboard", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminders_is_completed"), ["is_completed"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_is_overdue"), ["is_overdue"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminders_reminder_date"), ["reminder_date"], unique=False
        )

    op.create_table(
        "screenshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("extracted_data", cms.models.SafeJSON(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "spiderfoot_scans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=100), nullable=False),
        sa.Column("scan_name", sa.String(length=300), nullable=True),
        sa.Column("target_value", sa.String(length=500), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("use_case", sa.String(length=50), nullable=True),
        sa.Column("profile", sa.String(length=50), nullable=True),
        sa.Column("module_ids", cms.models.SafeJSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("result_summary", cms.models.SafeJSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("spiderfoot_scans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spiderfoot_scans_scan_id"), ["scan_id"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("financial_record_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("comment_type", sa.String(length=20), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("edit_count", sa.Integer(), nullable=True),
        sa.Column("last_edited_by_id", sa.String(length=36), nullable=True),
        sa.Column("last_edited_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["financial_record_id"],
            ["financial_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_edited_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=36), nullable=True),
        sa.Column("financial_record_id", sa.String(length=36), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=True),
        sa.Column("storage_type", sa.String(length=20), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", cms.models.SafeJSON(), nullable=True),
        sa.Column("classification", sa.String(length=20), nullable=True),
        sa.Column("uploaded_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["financial_record_id"],
            ["financial_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment_edit_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("comment_id", sa.String(length=36), nullable=False),
        sa.Column("previous_content", sa.Text(), nullable=False),
        sa.Column("new_content", sa.Text(), nullable=False),
        sa.Column("edited_by_id", sa.String(length=36), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edited_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_edit_history")
    op.drop_table("notifications")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))

    op.drop_table("documents")
    op.drop_table("comments")
    with op.batch_alter_table("spiderfoot_scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spiderfoot_scans_scan_id"))

    op.drop_table("spiderfoot_scans")
    op.drop_table("screenshots")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_reminder_date"))
        batch_op.drop_index(batch_op.f("ix_reminders_is_overdue"))
        batch_op.drop_index(batch_op.f("ix_reminders_is_completed"))

    op.drop_table("reminders")
    with op.batch_alter_table("osint_searches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_osint_searches_status"))
        batch_op.drop_index(batch_op.f("ix_osint_searches_search_id"))

    op.drop_table("osint_searches")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_subject_id"))
        batch_op.drop_index(batch_op.f("ix_findings_case_id"))

    op.drop_table("findings")
    op.drop_table("financial_records")
    op.drop_table("case_subjects")
    op.drop_table("case_assignments")
    op.drop_table("subject_relations")
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_social_accounts_username"))
        batch_op.drop_index(batch_op.f("ix_social_accounts_subject_id"))
        batch_op.drop_index(batch_op.f("ix_social_accounts_platform"))

    op.drop_table("social_accounts")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_key"))
        batch_op.drop_index(batch_op.f("ix_settings_category"))

    op.drop_table("settings")
    with op.batch_alter_table("phone_lookups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_phone_lookups_phone"))

    op.drop_table("phone_lookups")
    op.drop_table("document_templates")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_subject_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_client_id"))

    op.drop_table("contacts")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_title"))
        batch_op.drop_index(batch_op.f("ix_cases_client_id"))
        batch_op.drop_index(batch_op.f("ix_cases_case_number"))

    op.drop_table("cases")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    op.drop_table("api_keys")
    with op.batch_alter_table("addresses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_addresses_subject_id"))
        batch_op.drop_index(batch_op.f("ix_addresses_client_id"))

    op.drop_table("addresses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subjects_name"))

    op.drop_table("subjects")
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clients_name"))

    op.drop_table("clients")
    # ### end Alembic commands ###
