import re

CACHE_TTL_HOURS = 24

FALSE_POSITIVE_PATTERNS = [
    (
        re.compile(
            r"\b(not found|no results?|doesn\'t exist|not exist|user not found|profile not found|account not found|page not found|404)\b",
            re.I,
        ),
        False,
    ),
    (
        re.compile(
            r"\b(invalid user|user invalid|user does not|user hasn\'t|user has no|username not)\b",
            re.I,
        ),
        False,
    ),
    (
        re.compile(
            r"\b(removed this|content removed|deleted account|this account|has been|page removed)\b",
            re.I,
        ),
        False,
    ),
    (
        re.compile(
            r"(sign up|create account|log in|login).{0,50}(to view|to see)", re.I
        ),
        False,
    ),
    (
        re.compile(
            r"(view profile|profile).{0,30}(requires|need).{0,30}(login|sign in)", re.I
        ),
        False,
    ),
    (re.compile(r"error|404|403|400.{0,20}(page|content)", re.I), False),
]

CONFIRMATION_PATTERNS = [
    (re.compile(r"@" + "{username}" + r"\b", re.I), True),
    (re.compile(r'"username".{0,30}' + "{username}", re.I), True),
    (re.compile(r'"name".{0,30}' + "{username}", re.I), True),
]

PLATFORM_PRIORITY = {
    "Facebook": 1,
    "GitHub": 2,
    "Telegram": 3,
    "Steam": 4,
    "TikTok": 5,
    "Pinterest": 6,
    "Instagram": 7,
    "LinkedIn": 8,
    "Twitter/X": 9,
    "YouTube": 10,
    "Reddit": 11,
    "Snapchat": 12,
    "Discord": 13,
    "Twitch": 14,
    "Spotify": 15,
    "Tumblr": 16,
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Cache-Control": "max-age=0",
}

WHATSAPP_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

SHERLOCK_DATA_URL = "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json"

WHATSMYNAME_DATA_URL = (
    "https://raw.githubusercontent.com/WebBreacher/WhatsMyName/main/wmn-data.json"
)

WEBCAM_DATA = {
    "countries": [
        {"code": "us", "name": "United States"},
        {"code": "uk", "name": "United Kingdom"},
        {"code": "nl", "name": "Netherlands"},
        {"code": "de", "name": "Germany"},
        {"code": "fr", "name": "France"},
        {"code": "jp", "name": "Japan"},
        {"code": "au", "name": "Australia"},
        {"code": "ca", "name": "Canada"},
        {"code": "it", "name": "Italy"},
        {"code": "es", "name": "Spain"},
        {"code": "ch", "name": "Switzerland"},
        {"code": "at", "name": "Austria"},
        {"code": "be", "name": "Belgium"},
        {"code": "no", "name": "Norway"},
        {"code": "se", "name": "Sweden"},
    ],
    "webcams": [
        {
            "title": "Times Square",
            "location": "New York, US",
            "url": "https://www.earthcam.com/fanschoose/nyctimessquare/",
            "thumbnail": "https://videos-3.earthcam.com/fecnetwork/9974.flv/playlist.m3u8",
            "country": "us",
            "city": "new york",
            "type": "stream",
        },
        {
            "title": "Las Vegas Strip",
            "location": "Las Vegas, US",
            "url": "https://www.earthcam.com/fanschoose/vegasstrip/",
            "thumbnail": "https://videos-3.earthcam.com/fecnetwork/4018.flv/playlist.m3u8",
            "country": "us",
            "city": "las vegas",
            "type": "stream",
        },
        {
            "title": "South Beach",
            "location": "Miami Beach, US",
            "url": "https://www.earthcam.com/floridakeys/",
            "thumbnail": "https://videos-3.earthcam.com/fecnetwork/9974.flv/playlist.m3u8",
            "country": "us",
            "city": "miami",
            "type": "stream",
        },
        {
            "title": "French Quarter",
            "location": "New Orleans, US",
            "url": "https://www.earthcam.com/louisiana/bourbonstreet/",
            "thumbnail": "",
            "country": "us",
            "city": "new orleans",
            "type": "image",
        },
        {
            "title": "Santa Monica Pier",
            "location": "Santa Monica, US",
            "url": "https://www.santamonica.gov/places/santa-monica-pier-live-camera",
            "thumbnail": "",
            "country": "us",
            "city": "santa monica",
            "type": "image",
        },
        {
            "title": "Hawaii Beach",
            "location": "Honolulu, Hawaii, US",
            "url": "https://www.earthcam.com/hawaii/waikiki/",
            "thumbnail": "",
            "country": "us",
            "city": "honolulu",
            "type": "image",
        },
        {
            "title": "Denver Downtown",
            "location": "Denver, US",
            "url": "https://www.earthcam.com/colorado/denver/",
            "thumbnail": "",
            "country": "us",
            "city": "denver",
            "type": "image",
        },
        {
            "title": "Chicago Skyline",
            "location": "Chicago, US",
            "url": "https://www.earthcam.com/illinois/chicagobridgetower/",
            "thumbnail": "",
            "country": "us",
            "city": "chicago",
            "type": "image",
        },
        {
            "title": "Dam Square",
            "location": "Amsterdam, NL",
            "url": "https://www.amsterdam.nl/publish/pages/846657/live_camera.html",
            "thumbnail": "",
            "country": "nl",
            "city": "amsterdam",
            "type": "image",
        },
        {
            "title": "Leidseplein",
            "location": "Amsterdam, NL",
            "url": "https://www.amsterdam.nl/publish/pages/846657/live_camera.html",
            "thumbnail": "",
            "country": "nl",
            "city": "amsterdam",
            "type": "image",
        },
        {
            "title": "Keukenhof Tulips",
            "location": "Lisse, NL",
            "url": "https://www.keukenhof.nl/",
            "thumbnail": "",
            "country": "nl",
            "city": "lisse",
            "type": "image",
        },
        {
            "title": "Rotterdam Harbor",
            "location": "Rotterdam, NL",
            "url": "https://www.portofrotterdam.com/en/cameras",
            "thumbnail": "",
            "country": "nl",
            "city": "rotterdam",
            "type": "image",
        },
        {
            "title": "Tower Bridge",
            "location": "London, UK",
            "url": "https://www.earthcam.com/uk/london/",
            "thumbnail": "",
            "country": "uk",
            "city": "london",
            "type": "image",
        },
        {
            "title": "Abbey Road",
            "location": "London, UK",
            "url": "https://www.abbeyroad.com/crossing",
            "thumbnail": "",
            "country": "uk",
            "city": "london",
            "type": "image",
        },
        {
            "title": "Edinburgh Castle",
            "location": "Edinburgh, UK",
            "url": "https://www.edinburgh.gov.uk/cam1",
            "thumbnail": "",
            "country": "uk",
            "city": "edinburgh",
            "type": "image",
        },
        {
            "title": "Brighton Pier",
            "location": "Brighton, UK",
            "url": "https://www.brighton.gov.uk/",
            "thumbnail": "",
            "country": "uk",
            "city": "brighton",
            "type": "image",
        },
        {
            "title": "Eiffel Tower",
            "location": "Paris, FR",
            "url": "https://www.earthcam.com/fr/pariseiffeltower/",
            "thumbnail": "",
            "country": "fr",
            "city": "paris",
            "type": "image",
        },
        {
            "title": "Louvre",
            "location": "Paris, FR",
            "url": "https://www.earthcam.com/fr/parislouvre/",
            "thumbnail": "",
            "country": "fr",
            "city": "paris",
            "type": "image",
        },
        {
            "title": "Nice Beach",
            "location": "Nice, FR",
            "url": "https://www.nicetourisme.com/en/webcams",
            "thumbnail": "",
            "country": "fr",
            "city": "nice",
            "type": "image",
        },
        {
            "title": "Brandenburg Gate",
            "location": "Berlin, DE",
            "url": "https://www.earthcam.com/germany/berlin/",
            "thumbnail": "",
            "country": "de",
            "city": "berlin",
            "type": "image",
        },
        {
            "title": "Munich Marienplatz",
            "location": "Munich, DE",
            "url": "www.muenchen.de",
            "thumbnail": "",
            "country": "de",
            "city": "munich",
            "type": "image",
        },
        {
            "title": "Cologne Cathedral",
            "location": "Cologne, DE",
            "url": "https://www.koelntourguide.de/",
            "thumbnail": "",
            "country": "de",
            "city": "cologne",
            "type": "image",
        },
        {
            "title": "Shibuya Crossing",
            "location": "Tokyo, JP",
            "url": "https://www.shinjuku.life/",
            "thumbnail": "",
            "country": "jp",
            "city": "tokyo",
            "type": "image",
        },
        {
            "title": "Mount Fuji",
            "location": "Fujinomiya, JP",
            "url": "https://www.shizuoka-guide.com/",
            "thumbnail": "",
            "country": "jp",
            "city": "fuji",
            "type": "image",
        },
        {
            "title": "Nara Deer Park",
            "location": "Nara, JP",
            "url": "https://www.narakoubou.com/",
            "thumbnail": "",
            "country": "jp",
            "city": "nara",
            "type": "image",
        },
        {
            "title": "Sydney Harbour",
            "location": "Sydney, AU",
            "url": "https://www.sydney.com/",
            "thumbnail": "",
            "country": "au",
            "city": "sydney",
            "type": "image",
        },
        {
            "title": "Bondi Beach",
            "location": "Sydney, AU",
            "url": "https://www.bondi.nsw.gov.au/",
            "thumbnail": "",
            "country": "au",
            "city": "bondi",
            "type": "image",
        },
        {
            "title": "Melbourne CBD",
            "location": "Melbourne, AU",
            "url": "https://www.melbourne.vic.gov.au/",
            "thumbnail": "",
            "country": "au",
            "city": "melbourne",
            "type": "image",
        },
        {
            "title": "Colosseum",
            "location": "Rome, IT",
            "url": "https://www.earthcam.com/italy/rome/",
            "thumbnail": "",
            "country": "it",
            "city": "rome",
            "type": "image",
        },
        {
            "title": "Venice Canal",
            "location": "Venice, IT",
            "url": "https://www.italia.it/",
            "thumbnail": "",
            "country": "it",
            "city": "venice",
            "type": "image",
        },
        {
            "title": "Florence Duomo",
            "location": "Florence, IT",
            "url": "https://www.museodelduomo.org/",
            "thumbnail": "",
            "country": "it",
            "city": "florence",
            "type": "image",
        },
        {
            "title": "La Rambla",
            "location": "Barcelona, ES",
            "url": "https://www.barcelona-tourisme.com/",
            "thumbnail": "",
            "country": "es",
            "city": "barcelona",
            "type": "image",
        },
        {
            "title": "Plaza Mayor",
            "location": "Madrid, ES",
            "url": "https://www.esmadrid.com/",
            "thumbnail": "",
            "country": "es",
            "city": "madrid",
            "type": "image",
        },
        {
            "title": "Ibiza Beach",
            "location": "Ibiza, ES",
            "url": "https://www.ibiza.travel/",
            "thumbnail": "",
            "country": "es",
            "city": "ibiza",
            "type": "image",
        },
        {
            "title": "Zermatt Matterhorn",
            "location": "Zermatt, CH",
            "url": "www.zermatt.ch",
            "thumbnail": "",
            "country": "ch",
            "city": "zermatt",
            "type": "image",
        },
        {
            "title": "Jungfrau",
            "location": "Jungfraujoch, CH",
            "url": "www.jungfrau.ch",
            "thumbnail": "",
            "country": "ch",
            "city": "jungfrau",
            "type": "image",
        },
        {
            "title": "Vienna Square",
            "location": "Vienna, AT",
            "url": "https://www.wien.info/",
            "thumbnail": "",
            "country": "at",
            "city": "vienna",
            "type": "image",
        },
        {
            "title": "Salzburg Old Town",
            "location": "Salzburg, AT",
            "url": "https://www.salzburg.info/",
            "thumbnail": "",
            "country": "at",
            "city": "salzburg",
            "type": "image",
        },
        {
            "title": "Grand Place",
            "location": "Brussels, BE",
            "url": "https://www.brussels.be/",
            "thumbnail": "",
            "country": "be",
            "city": "brussels",
            "type": "image",
        },
        {
            "title": "Antwerp Harbor",
            "location": "Antwerp, BE",
            "url": "https://www.portofantwerp.com/",
            "thumbnail": "",
            "country": "be",
            "city": "antwerp",
            "type": "image",
        },
        {
            "title": "Bergen Harbor",
            "location": "Bergen, NO",
            "url": "https://www.visitbergen.com/",
            "thumbnail": "",
            "country": "no",
            "city": "bergen",
            "type": "image",
        },
        {
            "title": "Oslo Opera",
            "location": "Oslo, NO",
            "url": "https://www.oslo.com/",
            "thumbnail": "",
            "country": "no",
            "city": "oslo",
            "type": "image",
        },
        {
            "title": "Stockholm Old Town",
            "location": "Stockholm, SE",
            "url": "https://www.stockholm.se/",
            "thumbnail": "",
            "country": "se",
            "city": "stockholm",
            "type": "image",
        },
        {
            "title": "Gothenburg Harbor",
            "location": "Gothenburg, SE",
            "url": "https://www.goteborg.com/",
            "thumbnail": "",
            "country": "se",
            "city": "gothenburg",
            "type": "image",
        },
        {
            "title": "Niagara Falls",
            "location": "Ontario, CA",
            "url": "https://www.earthcam.com/canada/niagarafalls/",
            "thumbnail": "",
            "country": "ca",
            "city": "niagara",
            "type": "image",
        },
        {
            "title": "Vancouver Harbor",
            "location": "Vancouver, CA",
            "url": "https://www.portmetrovancouver.com/",
            "thumbnail": "",
            "country": "ca",
            "city": "vancouver",
            "type": "image",
        },
        {
            "title": "Toronto Skyline",
            "location": "Toronto, CA",
            "url": "https://www.toronto.ca/",
            "thumbnail": "",
            "country": "ca",
            "city": "toronto",
            "type": "image",
        },
    ],
}

__all__ = [
    "CACHE_TTL_HOURS",
    "FALSE_POSITIVE_PATTERNS",
    "CONFIRMATION_PATTERNS",
    "PLATFORM_PRIORITY",
    "HEADERS",
    "WHATSAPP_HEADERS",
    "SHERLOCK_DATA_URL",
    "WHATSMYNAME_DATA_URL",
    "WEBCAM_DATA",
]
